# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

variables:
  MY_API_KEY: $(MY_API_KEY)

steps:
- checkout: self

- script: |
    chmod +x ./scripts/deploy.sh
    ./scripts/deploy.sh
  displayName: 'Run deploy.sh script'
  env:
    MY_VAR: 'value'