- name: Deploy Express App Docker Container
  hosts: docker_hosts
  become: true
  tasks:
    - name: Ensure Docker service is running
      systemd:
        name: docker
        state: started
        enabled: true

    - name: Build and run the Docker container
      docker_container:
        name: express-app
        image: express-app
        state: started
        build:
          path: /home/MP20040674/Cloud-Server-Automation
        ports:
          - "3000:3000"
