- name: Deploy Express App Docker Container
  hosts: docker_hosts
  become: true
  tasks:
    - name: Start Docker service
      systemd:
        name: docker
        state: started
        enabled: true

   - name: Build Docker image on the server
    command: docker build -t express-app  /home/MP20040674/Cloud-Server-Automation

    - name: Pull Docker image from local build to the client
      copy:
        src: /home/MP20040674/Cloud-Server-Automation/
        dest: /usr/src/app
        mode: 0755

    - name: Run Docker container for sample app
      docker_container:
        name: express-app
        image: express-app
        state: started
        ports:
          - "3000:3000"
