- name: Deploy Sample App Docker Container
  hosts: your_server_ip
  become: true
  tasks:
    - name: Install Docker
      apt:
        name: docker.io
        state: present
        update_cache: yes

    - name: Start Docker service
      systemd:
        name: docker
        state: started
        enabled: true

    - name: Pull Docker image from local build
      copy:
        src: /path/to/your/local/sample-app
        dest: /path/on/remote/sample-app
        mode: 0755

    - name: Build Docker image on the server
      command: docker build -t sample-app /path/on/remote/sample-app

    - name: Run Docker container for sample app
      docker_container:
        name: sample-app
        image: sample-app
        state: started
        ports:
          - "3000:3000"
